### ISSUE TITLE
import FirebaseAnalytics.unitypackage and crash

### ISSUE THREAD

**Issue by stryper** [universal-tools/UTNotificationsFeedback#112]
2019-08-14 21:29:10.296 25696-25696/? I/zygote64: Rejecting re-init on previously-failed class java.lang.Class<com.google.firebase.messaging.FirebaseMessagingService>: java.lang.IllegalAccessError: Class com.google.firebase.iid.zzb extended by class com.google.firebase.messaging.FirebaseMessagingService is inaccessible (declaration of 'com.google.firebase.messaging.FirebaseMessagingService' appears in /data/app/com.smilegames.sutdaonline-7JttERNetg7gqPlK_H5sJA==/base.apk)
2019-08-14 21:29:10.304 25696-25696/? I/zygote64: Rejecting re-init on previously-failed class java.lang.Class<universal.tools.notifications.FCMService>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/messaging/FirebaseMessagingService;
2019-08-14 21:29:10.304 25696-25696/? I/zygote64: Caused by: java.lang.ClassNotFoundException: com.google.firebase.messaging.FirebaseMessagingService
2019-08-14 21:29:10.312 25696-25696/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.smilegames.sutdaonline, PID: 25696
    java.lang.RuntimeException: Unable to instantiate service universal.tools.notifications.FCMService: java.lang.ClassNotFoundException: Didn't find class "universal.tools.notifications.FCMService" on path: DexPathList[[zip file "/data/app/com.smilegames.sutdaonline-7JttERNetg7gqPlK_H5sJA==/base.apk"],nativeLibraryDirectories=[/data/app/com.smilegames.sutdaonline-7JttERNetg7gqPlK_H5sJA==/lib/arm64, /data/app/com.smilegames.sutdaonline-7JttERNetg7gqPlK_H5sJA==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3529)
        at android.app.ActivityThread.-wrap4(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1786)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "universal.tools.notifications.FCMService" on path: DexPathList[[zip file "/data/app/com.smilegames.sutdaonline-7JttERNetg7gqPlK_H5sJA==/base.apk"],nativeLibraryDirectories=[/data/app/com.smilegames.sutdaonline-7JttERNetg7gqPlK_H5sJA==/lib/arm64, /data/app/com.smilegames.sutdaonline-7JttERNetg7gqPlK_H5sJA==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3526)
        at android.app.ActivityThread.-wrap4(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1786) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6944) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) 
    Suppressed: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/messaging/FirebaseMessagingService;
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        ... 10 more
     Caused by: java.lang.ClassNotFoundException: com.google.firebase.messaging.FirebaseMessagingService
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        ... 13 more
     Caused by: java.lang.IllegalAccessError: Class com.google.firebase.iid.zzb extended by class com.google.firebase.messaging.FirebaseMessagingService is inaccessible (declaration of 'com.google.firebase.messaging.FirebaseMessagingService' appears in /data/app/com.smilegames.sutdaonline-7JttERNetg7gqPlK_H5sJA==/base.apk)

**Comment by yuriy-universal-ivanov** [comment]
Hi @stryper ,

See https://forum.unity.com/threads/released-utnotifications-professional-cross-platform-push-notifications-and-more.333045/page-17#post-4777697

Best regards,
Yuriy, Universal Tools team.

**Comment by yuriy-universal-ivanov** [comment]
Fixed in 1.8.3
