### ISSUE TITLE
Unable to instantiate receiver universal.tools.notifications.GcmBroadcastReceiver: java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by Bestlis** [universal-tools/UTNotificationsFeedback#15]
Hello!
When I try to send notification, I get error:

11-19 12:46:49.250  22625-22625/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.RuntimeException: Unable to instantiate receiver universal.tools.notifications.GcmBroadcastReceiver: java.lang.ClassNotFoundException: universal.tools.notifications.GcmBroadcastReceiver
            at android.app.ActivityThread.handleReceiver(ActivityThread.java:2218)
            at android.app.ActivityThread.access$1500(ActivityThread.java:133)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1279)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4797)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.ClassNotFoundException: universal.tools.notifications.GcmBroadcastReceiver
            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:61)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
            at android.app.ActivityThread.handleReceiver(ActivityThread.java:2213)
            at android.app.ActivityThread.access$1500(ActivityThread.java:133)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1279)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4797)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
            at dalvik.system.NativeStart.main(Native Method)

universal.tools.notifications.GcmBroadcastReceiver added to project!

What is my problem?
Thanks!

Update: when I decompile apk with apktool class exists.

**Comment by Bestlis** [comment]
SOLVED!

**Comment by Fournux** [comment]
Hi,

I have the same issue, how did you solve it ?

Thank you.

**Comment by Bestlis** [comment]
Check your manifest file.
Insert <service> first of all services you have.
Check all your permission and namespaces.

**Comment by Fournux** [comment]
Could you give me more details about permissions and namespaces, please ?
Do you remember what did you change ?

Thanks.

**Comment by yuriy-universal-ivanov** [comment]
Hi @Fournux,
I already answered you in the forum: please contact us by email. From the LogCat log you attached it looks like your Android manifest is configured wrong. Thing is, UTNotifications should do it for you automatically, when you configure it in Unity menu. What happened in your case is not completely clear for me, so having the sample .apk where an issue is being reproduced would be a big help.

I'm long for helping you as soon as possible, so I'm waiting for your email.

Best regards,
Yuriy Ivanov, Universal Tools team.

**Comment by yuriy-universal-ivanov** [comment]
@Fournux 
Or, at least, send the file Assets/Plugins/AndroidManifest.xml if you have one. And, more important, please tell if you don't have it at all.

Thank you! Hope I'll help you to fix that issue fast.

**Comment by Fournux** [comment]
I just sent you my Android manifest by email some minutes ago.

Thank you for your support.

**Comment by yuriy-universal-ivanov** [comment]
@Fournux 
Hi, did you receive my emails? I got an automated response:
This is an automatically generated Delivery Status Notification

THIS IS A WARNING MESSAGE ONLY.

YOU DO NOT NEED TO RESEND YOUR MESSAGE.

Delivery to the following recipient has been delayed:

```
 mailer-daemon@googlemail.com
```

Message will be retried for 2 more day(s)
