### ISSUE TITLE
Unity 5.4.0f3 - Issues with UTNotifications and Facebook Unity SDK

### ISSUE THREAD

**Issue by bitfabrikken** [universal-tools/UTNotificationsFeedback#27]
Hi, thanks for a great plugin!

I'm getting an error when I try to build for Android, errors occur on the step "Converting Java classes to dex format".

Plugins:
UTNotifications 1.5.4
Facebook Unity SDK 7.8.0

The error is as follows:

```
CommandInvokationFailure: Unable to convert classes into dex format.
C:\Program Files (x86)\Java\jdk1.7.0_40__\bin\java.exe -Xmx1024M -Dcom.android.sdkmanager.toolsdir="C:/android-sdk\tools" -Dfile.encoding=UTF8 -jar "C:\Program Files\Unity\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\sdktools.jar" -

stderr[
warning: Ignoring InnerClasses attribute for an anonymous inner class
(org.apache.commons.httpclient.HttpMethodBase$1) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.
warning: Ignoring InnerClasses attribute for an anonymous inner class
(org.apache.commons.httpclient.protocol.ControllerThreadSocketFactory$1) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoIcsImpl;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoJellyBeanMr2;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoStubImpl;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/app/ActionBarDrawerToggle;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/app/ActionBarDrawerToggle$1;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/app/ActionBarDrawerToggle$ActionBarDrawerToggleImpl;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/app/ActionBarDrawerToggle$ActionBarDrawerToggleImplBase;

UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.RuntimeException: Translation has been interrupted
    at com.android.dx.command.dexer.Main.processAllFiles(Main.java:608)
    at com.android.dx.command.dexer.Main.runMonoDex(Main.java:311)
    at com.android.dx.command.dexer.Main.run(Main.java:277)
    at com.android.dx.command.dexer.Main.main(Main.java:245)
    at com.android.dx.command.Main.main(Main.java:106)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at SDKMain.main(SDKMain.java:129)
Caused by: java.lang.InterruptedException: Too many errors
    at com.android.dx.command.dexer.Main.processAllFiles(Main.java:600)
    ... 9 more
]
stdout[
processing archive C:\Dropbox\unity\055 - Speed Dice\Temp\StagingArea\android-libraries\GooglePlay\libs\.\classes.jar...
ignored resource META-INF/
ignored resource META-INF/MANIFEST.MF
ignored resource com/
ignored resource com/android/
ignored resource com/android/vending/
ignored resource com/android/vending/billing/
processing com/android/vending/billing/IInAppBillingService.class...
processing com/android/vending/billing/IInAppBillingService$Stub.class...
processing com/android/vending/billing/IInAppBillingService$Stub$Proxy.class...
ignored resource com/unity/
ignored resource com/unity/purchasing/
ignored resource com/unity/purchasing/googleplay/
processing com/unity/purchasing/googleplay/ActivityLauncher.class...
processing com/unity/purchasing/googleplay/BillingServiceManager.class...
processing com/unity/purchasing/googleplay/BillingServiceManager$1.class...
processing com/unity/purchasing/googleplay/BillingServiceManager$1$1.class...
processing com/unity/purchasing/googleplay/BillingServiceManager$1$2.class...
processing com/unity/purchasing/googleplay/BillingServiceManager$2.class...
processing com/unity/purchasing/googleplay/BillingServiceProcessor.class...
processing com/unity/purchasing/googleplay/BuildConfig.class...
processing com/unity/purchasing/googleplay/Consts.class...
processing com/unity/purchasing/googleplay/Consts$PurchaseState.class...
processing com/unity/purchasing/googleplay/Consts$ResponseCode.class...
processing com/unity/purchasing/googleplay/GooglePlayBillingUnAvailableException.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing$1.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing$2.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing$3.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing$4.class...
processing com/unity/purchasing/googleplay/IActivityLauncher.class...
processing com/unity/purchasing/googleplay/IBillingServiceManager.class...
processing com/unity/purchasing/googleplay/IabException.class...
processing com/unity/purchasing/googleplay/IabHelper.class...
processing com/unity/purchasing/googleplay/IabHelper$1.class...
processing com/unity/purchasing/googleplay/IabHelper$2.class...
processing com/unity/purchasing/googleplay/IabHelper$3.class...
processing com/unity/purchasing/googleplay/IabHelper$4.class...
processing com/unity/purchasing/googleplay/IabHelper$OnConsumeFinishedListener.class...
processing com/unity/purchasing/googleplay/IabHelper$OnConsumeMultiFinishedListener.class...
processing com/unity/purchasing/googleplay/IabHelper$OnIabPurchaseFinishedListener.class...
processing com/unity/purchasing/googleplay/IabHelper$OnIabSetupFinishedListener.class...
processing com/unity/purchasing/googleplay/IabHelper$QueryInventoryFinishedListener.class...
processing com/unity/purchasing/googleplay/IabResult.class...
processing com/unity/purchasing/googleplay/Inventory.class...
processing com/unity/purchasing/googleplay/Purchase.class...
processing com/unity/purchasing/googleplay/PurchaseActivity.class...
processing com/unity/purchasing/googleplay/PurchaseFailedEvent.class...
processing com/unity/purchasing/googleplay/SkuDetails.class...
processing archive C:\Dropbox\unity\055 - Speed Dice\Temp\StagingArea\android-libraries\UTNotifications\bin\utnotifications.jar...
ignored resource META-INF/MANIFEST.MF
processing universal/tools/notifications/AdmBroadcastReceiver.class...
processing universal/tools/notifications/AdmIntentService.class...
processing universal/tools/notifications/AlarmBroadcastReceiver.class...
processing universal/tools/notifications/AmazonProvider.class...
processing universal/tools/notifications/GcmBroadcastReceiver.class...
processing universal/tools/notifications/GcmIntentService.class...
processing universal/tools/notifications/GooglePlayProvider.class...
processing universal/tools/notifications/GooglePlayProvider$1.class...
processing universal/tools/notifications/GooglePlayProvider$1$1.class...
processing universal/tools/notifications/Manager.class...
processing universal/tools/notifications/NotificationIntentService.class...
processing universal/tools/notifications/ScheduledNotificationsRestorer.class...
processing archive C:\Dropbox\unity\055 - Speed Dice\Temp\StagingArea\android-libraries\UTNotifications\libs\.\android-support-v4.jar...
ignored resource META-INF/
ignored resource META-INF/MANIFEST.MF
ignored resource android/
ignored resource android/support/
ignored resource android/support/annotation/
processing android/support/annotation/AnimRes.class...
processing android/support/annotation/AnimatorRes.class...
processing android/support/annotation/AnyRes.class...
processing android/support/annotation/ArrayRes.class...
processing android/support/annotation/AttrRes.class...
processing android/support/annotation/BoolRes.class...
processing android/support/annotation/ColorRes.class...
processing android/support/annotation/DimenRes.class...
processing android/support/annotation/DrawableRes.class...
processing android/support/annotation/FractionRes.class...
processing android/support/annotation/IdRes.class...
processing android/support/annotation/IntDef.class...
processing android/support/annotation/IntegerRes.class...
processing android/support/annotation/InterpolatorRes.class...
processing android/support/annotation/LayoutRes.class...
processing android/support/annotation/MenuRes.class...
processing android/support/annotation/NonNull.class...
processing android/support/annotation/Nullable.class...
processing android/support/annotation/PluralsRes.class...
processing android/support/annotation/RawRes.class...
processing android/support/annotation/StringDef.class...
processing android/support/annotation/StringRes.class...
processing android/support/annotation/StyleRes.class...
processing android/support/annotation/StyleableRes.class...
processing android/support/annotation/XmlRes.class...
ignored resource android/support/v4/
ignored resource android/support/v4/accessibilityservice/
processing android/support/v4/accessibilityservice/AccessibilityServiceInfoCompat.class...
processing android/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoIcsImpl.class...
processing android/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoJellyBeanMr2.class...
processing android/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoStubImpl.class...
processing android/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl.class...
processing android/support/v4/accessibilityservice/AccessibilityServiceInfoCompatIcs.class...
processing android/support/v4/accessibilityservice/AccessibilityServiceInfoCompatJellyBeanMr2.class...
ignored resource android/support/v4/app/
processing android/support/v4/app/ActionBarDrawerToggle.class...
processing android/support/v4/app/ActionBarDrawerToggle$1.class...
processing android/support/v4/app/ActionBarDrawerToggle$ActionBarDrawerToggleImpl.class...
processing android/support/v4/app/ActionBarDrawerToggle$ActionBarDrawerToggleImplBase.class...
processing android/support/v4/app/ActionBarDrawerToggle$ActionBarDrawerToggleImplHC.class...
processing android/support/v4/app/ActionBarDrawerToggle$ActionBarDrawerToggleImplJellybeanMR2.class...
processing android/support/v4/app/ActionBarDrawerToggle$Delegate.class...
processing android/support/v4/app/ActionBarDrawerToggle$DelegateProvider.class...
processing android/support/v4/app/ActionBarDrawerToggle$SlideDrawable.class...
processing android/support/v4/app/ActionBarDrawerToggleHoneycomb.class...
processing android/support/v4/app/ActionBarDrawerToggleHoneycomb$SetIndicatorInfo.class...
processing android/support/v4/app/ActionBarDrawerToggleJellybeanMR2.class...
processing android/support/v4/app/ActivityCompat.class...
processing android/support/v4/app/ActivityCompat$SharedElementCallback21Impl.class...
processing android/support/v4/app/ActivityCompat21.class...
processing android/support/v4/app/ActivityCompat21$SharedElementCallback21.class...
processing android/support/v4/app/ActivityCompat21$SharedElementCallbackImpl.class...
processing android/support/v4/app/ActivityCompatHoneycomb.class...
processing android/support/v4/app/ActivityCompatJB.class...
processing android/support/v4/app/ActivityManagerCompat.class...
processing android/support/v4/app/ActivityManagerCompatKitKat.class...
processing android/support/v4/app/ActivityOptionsCompat.class...
processing android/support/v4/app/ActivityOptionsCompat$ActivityOptionsImpl21.class...
processing android/support/v4/app/ActivityOptionsCompat$ActivityOptionsImplJB.class...
processing android/support/v4/app/ActivityOptionsCompat21.class...
processing android/support/v4/app/ActivityOptionsCompatJB.class...
processing android/support/v4/app/BackStackRecord.class...
processing android/support/v4/app/BackStackRecord$1.class...
processing android/support/v4/app/BackStackRecord$2.class...
processing android/support/v4/app/BackStackRecord$3.class...
processing android/support/v4/app/BackStackRecord$Op.class...
processing android/support/v4/app/BackStackRecord$TransitionState.class...
processing android/support/v4/app/BackStackState.class...
processing android/support/v4/app/BackStackState$1.class...
processing android/support/v4/app/BundleUtil.class...
processing android/support/v4/app/DialogFragment.class...
processing android/support/v4/app/DialogFragment$DialogStyle.class...
processing android/support/v4/app/Fragment.class...
processing android/support/v4/app/Fragment$1.class...
processing android/support/v4/app/Fragment$InstantiationException.class...
processing android/support/v4/app/Fragment$SavedState.class...
processing android/support/v4/app/Fragment$SavedState$1.class...
processing android/support/v4/app/FragmentActivity.class...
processing android/support/v4/app/FragmentActivity$1.class...
processing android/support/v4/app/FragmentActivity$2.class...
processing android/support/v4/app/FragmentActivity$NonConfigurationInstances.class...
processing android/support/v4/app/FragmentContainer.class...
processing android/support/v4/app/FragmentManager.class...
processing android/support/v4/app/FragmentManager$BackStackEntry.class...
processing android/support/v4/app/FragmentManager$OnBackStackChangedListener.class...
processing android/support/v4/app/FragmentManagerImpl.class...
processing android/support/v4/app/FragmentManagerImpl$1.class...
processing android/support/v4/app/FragmentManagerImpl$2.class...
processing android/support/v4/app/FragmentManagerImpl$3.class...
processing android/support/v4/app/FragmentManagerImpl$4.class...
processing android/support/v4/app/FragmentManagerImpl$5.class...
processing android/support/v4/app/FragmentManagerImpl$FragmentTag.class...
processing android/support/v4/app/FragmentManagerState.class...
processing android/support/v4/app/FragmentManagerState$1.class...
processing android/support/v4/app/FragmentPagerAdapter.class...
processing android/support/v4/app/FragmentState.class...
processing android/support/v4/app/FragmentState$1.class...
processing android/support/v4/app/FragmentStatePagerAdapter.class...
processing android/support/v4/app/FragmentTabHost.class...
processing android/support/v4/app/FragmentTabHost$1.class...
processing android/support/v4/app/FragmentTabHost$DummyTabFactory.class...
processing android/support/v4/app/FragmentTabHost$SavedState.class...
processing android/support/v4/app/FragmentTabHost$SavedState$1.class...
processing android/support/v4/app/FragmentTabHost$TabInfo.class...
processing android/support/v4/app/FragmentTransaction.class...
processing android/support/v4/app/FragmentTransaction$Transit.class...
processing android/support/v4/app/FragmentTransitionCompat21.class...
processing android/support/v4/app/FragmentTransitionCompat21$1.class...
processing android/support/v4/app/FragmentTransitionCompat21$2.class...
processing android/support/v4/app/FragmentTransitionCompat21$3.class...
processing android/support/v4/app/FragmentTransitionCompat21$4.class...
processing android/support/v4/app/FragmentTransitionCompat21$EpicenterView.class...
processing android/support/v4/app/FragmentTransitionCompat21$ViewRetriever.class...
processing android/support/v4/app/INotificationSideChannel.class...
```

**Comment by yuriy-universal-ivanov** [comment]
Hi @bitfabrikken,

First of all, thank you for using UTNotifications!

Your issue is caused by duplicating the Android Support Library (one copy comes with UTNotifications and another with Facebook SDK). To solve it, you just need to delete an extra copy of this library: Assets/Plugins/Android/UTNotifications/libs/android-support-v4.jar.

It should help.

Feel free to ask for any further support, I'm always happy to help.

Best regards,
Yuriy, Universal Tools team.

**Comment by bitfabrikken** [comment]
Thanks, that did the trick!
My game has suddenly started asking to access contacts on Android M - that couldn't be UTNotifications, right?

**Comment by yuriy-universal-ivanov** [comment]
Hi @bitfabrikken ,

Actually that could: our sample script uses Unity's **SystemInfo.deviceUniqueIdentifier** to identify devices with DemoServer, and the current Android implementation of this property by Unity uses telephony permission on Android 6. You may safely remove the whole sample code and scene from your application after finishing configuring push notifications services. The primary code of UTNotifications doesn't use any telephony related API.

**Comment by bitfabrikken** [comment]
Thank you very much once again :)
