### ISSUE TITLE
Error when trying to build

### ISSUE THREAD

**Issue by avinash2k** [universal-tools/UTNotificationsFeedback#28]
CommandInvokationFailure: Unable to convert classes into dex format. See the Console for details.
/Library/Java/JavaVirtualMachines/jdk1.7.0_71.jdk/Contents/Home/bin/java -Xmx2048M -Dcom.android.sdkmanager.toolsdir="/Users/avinash/Development/android-sdk-macosx/tools" -Dfile.encoding=UTF8 -jar "/Applications/Unity5.3.4/PlaybackEngines/AndroidPlayer/Tools/sdktools.jar" -

stderr[
warning: Ignoring InnerClasses attribute for an anonymous inner class
(org.apache.commons.httpclient.HttpMethodBase$1) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is _not_ an inner class.
warning: Ignoring InnerClasses attribute for an anonymous inner class
(org.apache.commons.httpclient.protocol.ControllerThreadSocketFactory$1) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is _not_ an inner class.
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/annotation/InterpolatorRes;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/annotation/RawRes;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/annotation/FractionRes;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/annotation/NonNull;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/annotation/PluralsRes;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/annotation/AttrRes;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/annotation/DrawableRes;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/annotation/AnyRes;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/annotation/IntegerRes;

UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.RuntimeException: Translation has been interrupted
    at com.android.dx.command.dexer.Main.processAllFiles(Main.java:608)
    at com.android.dx.command.dexer.Main.runMonoDex(Main.java:311)
    at com.android.dx.command.dexer.Main.run(Main.java:277)
    at com.android.dx.command.dexer.Main.main(Main.java:245)
    at com.android.dx.command.Main.main(Main.java:106)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at SDKMain.main(SDKMain.java:129)
Caused by: java.lang.InterruptedException: Too many errors
    at com.android.dx.command.dexer.Main.processAllFiles(Main.java:600)
    ... 9 more
]
stdout[
processing archive bin/classes.jar...
processing com/unity3d/player/a$1.class...
processing com/unity3d/player/a$2.class...
processing com/unity3d/player/a$a.class...
processing com/unity3d/player/a.class...
processing com/unity3d/player/b$1.class...
processing com/unity3d/player/b$2.class...
processing com/unity3d/player/b.class...
processing com/unity3d/player/c.class...
processing com/unity3d/player/d$1.class...
processing com/unity3d/player/d$2.class...
processing com/unity3d/player/d.class...
processing com/unity3d/player/e.class...
processing com/unity3d/player/f.class...
processing com/unity3d/player/g.class...
processing com/unity3d/player/h.class...
processing com/unity3d/player/i.class...
processing com/unity3d/player/j.class...
processing com/unity3d/player/k$1.class...
processing com/unity3d/player/k$2$1$1.class...
processing com/unity3d/player/k$2$1.class...
processing com/unity3d/player/k$2.class...
processing com/unity3d/player/k.class...
processing com/unity3d/player/l$1.class...
processing com/unity3d/player/l.class...
processing com/unity3d/player/m.class...
processing com/unity3d/player/n$1.class...
processing com/unity3d/player/n.class...
processing com/unity3d/player/o.class...
processing com/unity3d/player/p$1.class...
processing com/unity3d/player/p.class...
processing com/unity3d/player/NativeLoader.class...
processing com/unity3d/player/q.class...
processing com/unity3d/player/ReflectionHelper$1.class...
processing com/unity3d/player/ReflectionHelper$a.class...
processing com/unity3d/player/ReflectionHelper.class...
processing com/unity3d/player/r.class...
processing com/unity3d/player/s$1.class...
processing com/unity3d/player/s$2.class...
processing com/unity3d/player/s$3.class...
processing com/unity3d/player/s.class...
processing com/unity3d/player/t.class...
processing com/unity3d/player/u.class...
processing com/unity3d/player/UnityPlayer$1.class...
processing com/unity3d/player/UnityPlayer$2.class...
processing com/unity3d/player/UnityPlayer$4.class...
processing com/unity3d/player/UnityPlayer$5.class...
processing com/unity3d/player/UnityPlayer$6.class...
processing com/unity3d/player/UnityPlayer$7.class...
processing com/unity3d/player/UnityPlayer$8.class...
processing com/unity3d/player/UnityPlayer$9.class...
processing com/unity3d/player/UnityPlayer$10.class...
processing com/unity3d/player/UnityPlayer$11.class...
processing com/unity3d/player/UnityPlayer$12.class...
processing com/unity3d/player/UnityPlayer$13.class...
processing com/unity3d/player/UnityPlayer$14.class...
processing com/unity3d/player/UnityPlayer$3.class...
processing com/unity3d/player/UnityPlayer$15$1.class...
processing com/unity3d/player/UnityPlayer$15.class...
processing com/unity3d/player/UnityPlayer$16.class...
processing com/unity3d/player/UnityPlayer$17.class...
processing com/unity3d/player/UnityPlayer$18.class...
processing com/unity3d/player/UnityPlayer$19.class...
processing com/unity3d/player/UnityPlayer$20.class...
processing com/unity3d/player/UnityPlayer$a.class...
processing com/unity3d/player/UnityPlayer$b.class...
processing com/unity3d/player/UnityPlayer$c.class...
processing com/unity3d/player/UnityPlayer.class...
processing com/unity3d/player/UnityPlayerActivity.class...
processing com/unity3d/player/UnityPlayerNativeActivity.class...
processing com/unity3d/player/UnityPlayerProxyActivity.class...
processing com/unity3d/player/v.class...
processing com/unity3d/player/UnityWebRequest.class...
processing com/unity3d/player/w$1.class...
processing com/unity3d/player/w.class...
processing com/unity3d/player/WWW.class...
processing org/fmod/FMODAudioDevice.class...
processing org/fmod/a.class...
processing bitter/jnibridge/JNIBridge$a.class...
processing bitter/jnibridge/JNIBridge.class...
processing bin/classes/./android/support/v4/R$attr.class...
processing bin/classes/./android/support/v4/R$color.class...
processing bin/classes/./android/support/v4/R$drawable.class...
processing bin/classes/./android/support/v4/R$id.class...
processing bin/classes/./android/support/v4/R$integer.class...
processing bin/classes/./android/support/v4/R$layout.class...
processing bin/classes/./android/support/v4/R$string.class...
processing bin/classes/./android/support/v4/R$style.class...
processing bin/classes/./android/support/v4/R$styleable.class...
processing bin/classes/./android/support/v4/R.class...
processing bin/classes/./com/google/android/gms/auth/R$attr.class...
processing bin/classes/./com/google/android/gms/auth/R$color.class...
processing bin/classes/./com/google/android/gms/auth/R$drawable.class...
processing bin/classes/./com/google/android/gms/auth/R$id.class...
processing bin/classes/./com/google/android/gms/auth/R$integer.class...
processing bin/classes/./com/google/android/gms/auth/R$layout.class...
processing bin/classes/./com/google/android/gms/auth/R$string.class...
processing bin/classes/./com/google/android/gms/auth/R$style.class...
processing bin/classes/./com/google/android/gms/auth/R$styleable.class...
processing bin/classes/./com/google/android/gms/auth/R.class...
processing bin/classes/./com/google/android/gms/base/R$attr.class...
processing bin/classes/./com/google/android/gms/base/R$color.class...
processing bin/classes/./com/google/android/gms/base/R$drawable.class...
processing bin/classes/./com/google/android/gms/base/R$id.class...
processing bin/classes/./com/google/android/gms/base/R$integer.class...
processing bin/classes/./com/google/android/gms/base/R$layout.class...
processing bin/classes/./com/google/android/gms/base/R$string.class...
processing bin/classes/./com/google/android/gms/base/R$style.class...
processing bin/classes/./com/google/android/gms/base/R$styleable.class...
processing bin/classes/./com/google/android/gms/base/R.class...
processing bin/classes/./com/google/android/gms/drive/R$attr.class...
processing bin/classes/./com/google/android/gms/drive/R$color.class...
processing bin/classes/./com/google/android/gms/drive/R$drawable.class...
processing bin/classes/./com/google/android/gms/drive/R$id.class...
processing bin/classes/./com/google/android/gms/drive/R$integer.class...
processing bin/classes/./com/google/android/gms/drive/R$layout.class...
processing bin/classes/./com/google/android/gms/drive/R$string.class...
processing bin/classes/./com/google/android/gms/drive/R$style.class...
processing bin/classes/./com/google/android/gms/drive/R$styleable.class...
processing bin/classes/./com/google/android/gms/drive/R.class...
processing bin/classes/./com/google/android/gms/games/R$attr.class...
processing bin/classes/./com/google/android/gms/games/R$color.class...
processing bin/classes/./com/google/android/gms/games/R$drawable.class...
processing bin/classes/./com/google/android/gms/games/R$id.class...
processing bin/classes/./com/google/android/gms/games/R$integer.class...
processing bin/classes/./com/google/android/gms/games/R$layout.class...
processing bin/classes/./com/google/android/gms/games/R$string.class...
processing bin/classes/./com/google/android/gms/games/R$style.class...
processing bin/classes/./com/google/android/gms/games/R$styleable.class...
processing bin/classes/./com/google/android/gms/games/R.class...
processing bin/classes/./com/google/android/gms/nearby/R$attr.class...
processing bin/classes/./com/google/android/gms/nearby/R$color.class...
processing bin/classes/./com/google/android/gms/nearby/R$drawable.class...
processing bin/classes/./com/google/android/gms/nearby/R$id.class...
processing bin/classes/./com/google/android/gms/nearby/R$integer.class...
processing bin/classes/./com/google/android/gms/nearby/R$layout.class...
processing bin/classes/./com/google/android/gms/nearby/R$string.class...
processing bin/classes/./com/google/android/gms/nearby/R$style.class...
processing bin/classes/./com/google/android/gms/nearby/R$styleable.class...
processing bin/classes/./com/google/android/gms/nearby/R.class...
processing bin/classes/./com/google/android/gms/R$attr.class...
processing bin/classes/./com/google/android/gms/R$color.class...
processing bin/classes/./com/google/android/gms/R$drawable.class...
processing bin/classes/./com/google/android/gms/R$id.class...
processing bin/classes/./com/google/android/gms/R$integer.class...
processing bin/classes/./com/google/android/gms/R$layout.class...
processing bin/classes/./com/google/android/gms/R$string.class...
processing bin/classes/./com/google/android/gms/R$style.class...
processing bin/classes/./com/google/android/gms/R$styleable.class...
processing bin/classes/./com/google/android/gms/R.class...
processing bin/classes/./com/google/android/gms/tasks/R$attr.class...
processing bin/classes/./com/google/android/gms/tasks/R$color.class...
processing bin/classes/./com/google/android/gms/tasks/R$drawable.class...
processing bin/classes/./com/google/android/gms/tasks/R$id.class...
processing bin/classes/./com/google/android/gms/tasks/R$integer.class...
processing bin/classes/./com/google/android/gms/tasks/R$layout.class...
processing bin/classes/./com/google/android/gms/tasks/R$string.class...
processing bin/classes/./com/google/android/gms/tasks/R$style.class...
processing bin/classes/./com/google/android/gms/tasks/R$styleable.class...
processing bin/classes/./com/google/android/gms/tasks/R.class...
processing bin/classes/./com/google/example/games/mainlibproj/R$attr.class...
processing bin/classes/./com/google/example/games/mainlibproj/R$color.class...
processing bin/classes/./com/google/example/games/mainlibproj/R$drawable.class...
processing bin/classes/./com/google/example/games/mainlibproj/R$id.class...
processing bin/classes/./com/google/example/games/mainlibproj/R$integer.class...
processing bin/classes/./com/google/example/games/mainlibproj/R$layout.class...
processing bin/classes/./com/google/example/games/mainlibproj/R$string.class...
processing bin/classes/./com/google/example/games/mainlibproj/R$style.class...
processing bin/classes/./com/google/example/games/mainlibproj/R$styleable.class...
processing bin/classes/./com/google/example/games/mainlibproj/R.class...
processing bin/classes/./com/google/firebase/R$attr.class...
processing bin/classes/./com/google/firebase/R$color.class...
processing bin/classes/./com/google/firebase/R$drawable.class...
processing bin/classes/./com/google/firebase/R$id.class...
processing bin/classes/./com/google/firebase/R$integer.class...
processing bin/classes/./com/google/firebase/R$layout.class...
processing bin/classes/./com/google/firebase/R$string.class...
processing bin/classes/./com/google/firebase/R$style.class...
processing bin/classes/./com/google/firebase/R$styleable.class...
processing bin/classes/./com/google/firebase/R.class...
processing bin/classes/./com/pixtell/candygliders/R$attr.class...
processing bin/classes/./com/pixtell/candygliders/R$color.class...
processing bin/classes/./com/pixtell/candygliders/R$drawable.class...
processing bin/classes/./com/pixtell/candygliders/R$id.class...
processing bin/classes/./com/pixtell/candygliders/R$integer.class...
processing bin/classes/./com/pixtell/candygliders/R$layout.class...
processing bin/classes/./com/pixtell/candygliders/R$string.class...
processing bin/classes/./com/pixtell/candygliders/R$style.class...
processing bin/classes/./com/pixtell/candygliders/R$styleable.class...
processing bin/classes/./com/pixtell/candygliders/R.class...
processing bin/classes/./com/unity3d/ads/android/R$attr.class...
processing bin/classes/./com/unity3d/ads/android/R$color.class...
processing bin/classes/./com/unity3d/ads/android/R$drawable.class...
processing bin/classes/./com/unity3d/ads/android/R$id.class...
processing bin/classes/./com/unity3d/ads/android/R$integer.class...
processing bin/classes/./com/unity3d/ads/android/R$layout.class...
processing bin/classes/./com/unity3d/ads/android/R$string.class...
processing bin/classes/./com/unity3d/ads/android/R$style.class...
processing bin/classes/./com/unity3d/ads/android/R$styleable.class...
processing bin/classes/./com/unity3d/ads/android/R.class...
processing bin/classes/./universal/tools/notifications/R$attr.class...
processing bin/classes/./universal/tools/notifications/R$color.class...
processing bin/classes/./universal/tools/notifications/R$drawable.class...
processing bin/classes/./universal/tools/notifications/R$id.class...
processing bin/classes/./universal/tools/notifications/R$integer.class...
processing bin/classes/./universal/tools/notifications/R$layout.class...
processing bin/classes/./universal/tools/notifications/R$string.class...
processing bin/classes/./universal/tools/notifications/R$style.class...
processing bin/classes/./universal/tools/notifications/R$styleable.class...
processing bin/classes/./universal/tools/notifications/R.class...
processing archive plugins/./annotations-2.0.3.jar...
ignored<message truncated>

**Comment by avinash2k** [comment]
I have the latest google play services plugin from here : https://github.com/playgameservices/play-games-plugin-for-unity

**Comment by avinash2k** [comment]
Worked after i deleted the support jar file inside the lib folder of Unotifications
