### ISSUE TITLE
Sometimes disabling "Push Notifications" may not work (GCM)

### ISSUE THREAD

**Issue by yuriy-universal-ivanov** [universal-tools/UTNotificationsFeedback#6]
If the manifest doesn't contain push-notifications related lines and push notifications are disabled, they still can try to be initialized:
### Stacktrace:

E/AndroidRuntime(24348): Caused by: java.lang.SecurityException: Not allowed to start service Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms (has extras) } without permission com.google.android.c2dm.permission.RECEIVE
E/AndroidRuntime(24348):    at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1716)
E/AndroidRuntime(24348):    at android.app.ContextImpl.startService(ContextImpl.java:1693)
E/AndroidRuntime(24348):    at android.content.ContextWrapper.startService(ContextWrapper.java:516)
E/AndroidRuntime(24348):    at com.google.android.gms.gcm.GoogleCloudMessaging.zzt(Unknown Source)
E/AndroidRuntime(24348):    at com.google.android.gms.gcm.GoogleCloudMessaging.register(Unknown Source)
E/AndroidRuntime(24348):    at universal.tools.notifications.GooglePlayProvider$1.doInBackground(GooglePlayProvider.java:89)
E/AndroidRuntime(24348):    at universal.tools.notifications.GooglePlayProvider$1.doInBackground(GooglePlayProvider.java:1)
E/AndroidRuntime(24348):    at android.os.AsyncTask$2.call(AsyncTask.java:292)
E/AndroidRuntime(24348):    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/AndroidRuntime(24348):    ... 4 more

**Comment by yuriy-universal-ivanov** [comment]
Fixed in 1.2
